[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "2WGocoPnfAsMh3HjJ1hqn3ZniFoymzKkHWorcAM3Bcro"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/billy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
