[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "CoA6pQ7J8K4YVWLtk2EDapNb4wF73G3FXcVXdrnYVVQU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/billy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
